//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MJAroundTheWorld
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LocationImagesEntities : DbContext
    {
        public LocationImagesEntities()
            : base("name=LocationImagesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Photo> Photos { get; set; }
        public virtual DbSet<PhotoImage> PhotoImages { get; set; }
    
        public virtual ObjectResult<GetAllUsedCityStates_Result> GetAllUsedCityStates()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllUsedCityStates_Result>("GetAllUsedCityStates");
        }
    }
}
